---

- name: Validate bigip_ha_cluster_hostname and bigip_ha_cluster_peer_hostname present
  fail:
    msg: "The hostname parameters for the HA are not defined."
  when:
    - bigip_ha_cluster_hostname is not defined or bigip_ha_cluster_peer_hostname is not defined

- name: Validate bigip_ha_cluster_device_group present
  fail:
    msg: "The bigip_ha_cluster_device_group parameter is not defined."
  when:
    - bigip_ha_cluster_device_group is not defined
